# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "xenial-current"
  config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"
  config.vm.synced_folder ".", "/vagrant", nfs: true
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.define "dev", primary: true do |dev|
    config.vm.network "private_network", ip: "172.16.10.16"
    config.vm.network :forwarded_port, guest: 5432, host: 15432
    config.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "provisioning/playbook.yml"
      ansible.inventory_path = "provisioning/development"
      ansible.limit = "all"
    end
  end
end
